### ISSUE TITLE
Tree.__contains__ rationale

### ISSUE THREAD

**Issue by cowo78** [caesar0301/treelib#110]
I see that `Tree.__contains__` current implementation is:

    return [node for node in self._nodes
                if node == identifier]

If I am not mistaken this:
* visits every node, which is unnecessary since we can simply lookup the identifier
* returns a list while `object.__contains__` is only expected to return True or False

This is also trivial to fix and I can provide a patch, unless there's something I am missing

**Comment by leonardbinet** [comment]
@cowo78, good point, this has been fixed in https://github.com/caesar0301/treelib/pull/129/
