### ISSUE TITLE
What is the most efficient way to get all nodes in a certain depth

### ISSUE THREAD

**Issue by tonyliangli** [caesar0301/treelib#147]
Hi,

Thanks for the great lib. I would like to know how to get all nodes in a certain depth. I tried expand_tree with mode width, but i can only get nodes. I have to use level() to check the level. Please tell me if there's a better way. Thanks!

**Comment by leonardbinet** [comment]
Hi @tonyliangli , can you precise what is the expected output?
Do you want list of nodes at a given depth or do you want a tree truncated at a given depth?

**Comment by tonyliangli** [comment]
Thanks for the reply, I would like a list of nodes at a given depth. Is expand_tree with filter the only way?




| |
Tony Li
|
|
tonyliangli@163.com
|
On 03/02/2020 14:36, Léonard Binet wrote:

Hi @tonyliangli , can you precise what is the expected output?
Do you want list of nodes at a given depth or do you want a tree truncated at a given depth?

**Comment by leonardbinet** [comment]
Sorry for late reply, you can use `filter_nodes` method:
```
depth_2_nodes = list(t.filter_nodes(lambda x: t.depth(x) == 2))
```

**Comment by tonyliangli** [comment]
Got it. Thanks a lot.




| |
Tony Li
|
|
tonyliangli@163.com
|
On 03/09/2020 10:37, Léonard Binet wrote:

Sorry for late reply, you can use filter_nodes method:

depth_2_nodes = list(t.filter_nodes(lambda x: t.depth(x) == 2))
