### ISSUE TITLE
what is the purpose of "__real_true" method?

### ISSUE THREAD

**Issue by leonardbinet** [caesar0301/treelib#150]
In `Tree` class, the `__real_true` method only returns `True`, I don't understand at all in which use case it can be helpful :)

**Comment by caesar0301** [comment]
> In `Tree` class, the `__real_true` method only returns `True`, I don't understand at all in which use case it can be helpful :)

This can be safely replaced by `lambda` func to fulfill `expand_tree()`'s filter functionality
