### ISSUE TITLE
https://treelib.readthedocs.io/en/latest/ shows treelib 1.5.5 instead of 1.6.1

### ISSUE THREAD

**Issue by gmiretti** [caesar0301/treelib#174]
If there is something that I can do to help, let me know.

PD: Nice work

**Comment by liamlundy** [comment]
> If there is something that I can do to help, let me know.
> 
> PD: Nice work

Is this still showing up incorrectly? If so, lmk and I can adjust it. Otherwise I'll just go ahead and close this issue. Thanks for reporting and sorry for the long delay in response! :)
