### ISSUE TITLE
how to insert a node in a tree?

### ISSUE THREAD

**Issue by terry-jt** [caesar0301/treelib#197]
What's the simple way to insert a node in a tree? I do not find a direct API. Thanks.

**Comment by liamlundy** [comment]
In the basic usage section there is an example of how to add a code to the tree: https://treelib.readthedocs.io/en/latest/#basic-usage

If you want to create a node and then add it, you can do the following:
```py
node = Node(identifier=1, tag="One")
tree.add_node(node)
```

Lmk if you have any other questions or if we can close this issue. Thanks!

**Comment by liamlundy** [comment]
Closed due to inactivity
