### ISSUE TITLE
Update python version support!

### ISSUE THREAD

**Issue by panagiotisanagnostou** [caesar0301/treelib#202]
Hello everyone!

I am a fellow developer and I have developed a python package using this one on its core, for tree creation purposes.

I have tested your package in the newer version of python and until now it works perfectly.

Is it possible for me to suggest you doing an update on the supporting platforms  to include all the newer version of python?

It would a huge help for me to know that this package is up to your coding standards for python 3.9 and 3.10.

Thank you very much!

**Comment by caesar0301** [comment]
Fixed by https://github.com/caesar0301/treelib/pull/209

**Comment by panagiotisanagnostou** [comment]
Thank you very much for the fix!!!
