### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bornio** [caesar0301/treelib#38]
python3.4, OSX 10.10

```python
>>> from treelib import Tree, Node
>>> tree = Tree()
>>> tree.create_node("Harry", "harry")
>>> tree.create_node("Jane", "jane", parent="harry")
>>> tree.show()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/treelib/tree.py", line 517, in show
    func=print)
  File "/usr/local/lib/python3.4/site-packages/treelib/tree.py", line 560, in _print_backend
    if idhidden \
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by wandaboyer** [comment]
Still encountering this problem with Python 3.4 using treelib 1.3.0... Am I doing something wrong here? Thanks for the great library, and sorry for the hassle! :) :+1:

**Comment by caesar0301** [comment]
Thanks for your feedback. Its frustrating to solve the coding problem across versions, still no elegant solution. Expect that Python's API will be stable after current version and I can find an easy fix.

**Comment by wandaboyer** [comment]
Thanks so much for your help, and for the work you've put into this excellent package!

**Comment by caesar0301** [comment]
You are welcome! :+1:

**Comment by caesar0301** [comment]
To solve the string compatibility between Python 2.x and 3.x, treelib follows the way of porting Python 3.x to 2/3. That means, all strings are manipulated as unicode and you do not need `u''` prefix anymore. The impacted functions include `str()`, `show()` and `save2file()` routines. But if your data contains non-ascii characters and Python 2.x is used, you have to trigger the compatibility by declaring unicode_literals in the code:

    from __future__ import unicode_literals
