### ISSUE TITLE
test code coverage

### ISSUE THREAD

**Issue by carocad** [caesar0301/treelib#43]
Hey Xiaming
Could it be possible for you to enable the use of code coverage for the library with Coveralls?
I don't know if you know it, but with it you can check how much of your code is being covered with your tests. 

It is for free for open source projects and you can use your github account to use it.

Check it here: https://coveralls.io/

Cheers

**Comment by caesar0301** [comment]
Thanks for you advice. I heard about that testing service before.  I did not use that because treelib was a small module. But I think its a good way to cooperating with community and I will give it a try later. 

Thanks. :)
