### ISSUE TITLE
Dot export crashes when node tag is not a string

### ISSUE THREAD

**Issue by Miguellissimo** [caesar0301/treelib#52]
When creating a tree which does not hold string objects the export to the dot file format crashes.
See the minimal working example below

``` python
import treelib
from treelib.plugins import export_to_dot

t = treelib.Tree()
t.create_node([1,2,3])
export_to_dot(t, 'mwe.dot')
```

**Comment by Miguellissimo** [comment]
The problem is caused [here](https://github.com/caesar0301/treelib/blob/6d6c4670ad1f979266a7fbeff20856957b360f31/treelib/plugins.py#L18). ```tree[n].tag``` expects to hold a string which it does not in the code above. I don't know how to get it done across the different python versions but it would be nice to always get the string representation of the object.

**Comment by caesar0301** [comment]
You are right. Its an annoying issue to address encoding across python versions. But the problem is more severe. I will fix it later. Thanks

**Comment by villmow** [comment]
I just stumbled over the same problem, but I wonder why is this a problem across different python versions. To fix it you just need to add `str(nid)`/ `str(cid)` while constructing the state and connection.

**Comment by caesar0301** [comment]
OK Thanks @villmow

**Comment by villmow** [comment]
Btw. if your node tag contains quotes, this will produce an invalid dot file. You should escape quotes in the tag before formatting.
