### ISSUE TITLE
How to use this with mysql ?

### ISSUE THREAD

**Issue by levanlau** [caesar0301/treelib#69]
Hi,
I need to work with mysql database but i can not know how to query insert, delete , show data.
The examples is only run on console. So, how to interact on mysql database with django? I am a newbie on django.
Thank you.

**Comment by Natim** [comment]
Hi @levanlau 

If you are looking at storing trees in a relational database you should look at the MPTT design pattern. That's the best way of doing so.

With django you have the django-mptt package that let you do that easily.

**Comment by levanlau** [comment]
Thank you, Natim. I found it.
