### ISSUE TITLE
tree.to_json() method not working

### ISSUE THREAD

**Issue by asram6** [caesar0301/treelib#75]
Hi,
I saw in the documentation that the Tree object has a method to_json(). However, when I create a Tree object and try calling this method, I get the error: "'Tree' object has no attribute 'to_json'"

Am I missing something?

Thanks

**Comment by caesar0301** [comment]
Please show me your code snippet. It is actually there. If you have an old version of treelib (currently 1.3.7), please update with `pip install -U treelib`

**Comment by caesar0301** [comment]
Dup as #85
