### ISSUE TITLE
Read only?

### ISSUE THREAD

**Issue by kierun** [caesar0301/treelib#76]
Is there a way to make a tree read only?

I want to build a tree of data and let users lose on it. Since they are users, I want to make sure that they cannot change what is in the tree… Whether they want to or not!

Is this possible?

**Comment by c0fec0de** [comment]
FYI: http://anytree.readthedocs.io/en/2.4.2/tricks/readonly.html

**Comment by liamlundy** [comment]
Since this is a python library, there is always going to be the opportunity for users to modify object attributes etc. I'm not not totally sure I understand your use case however?

**Comment by kierun** [comment]
> Since this is a python library, there is always going to be the opportunity for users to modify object attributes etc. I'm not not totally sure I understand your use case however?

Oh dear, this is 5 years old… Better close it.
