### ISSUE TITLE
Load tree from json

### ISSUE THREAD

**Issue by Hades1996** [caesar0301/treelib#78]
Is there any way to restaure, load,or parse a tree from json, string or file?

After all we already have those methods for to save an existing tree object, it would be useful.

Thanks for your work

**Comment by ocervell** [comment]
This would be great if someone could implement it.
For large trees, recreating the tree everytime is really slow, making it impossible to do live-updates ...
I use treelib to create a JSTree that is consumed by a web interface, the tree is 170k+ nodes and re-creating it takes a while (7 minutes).

**Comment by athulmurali** [comment]
Yup. It's a great idea. I would love to work on it.   This might be greatly helpful for crawling web trees.

**Comment by ocervell** [comment]
Yes, as well as dynamically changing some node attributes and re-saving the tree to the file, without having to recompute everything.

**Comment by caesar0301** [comment]
Dup #85
