### ISSUE TITLE
tree.show prints a byte literal

### ISSUE THREAD

**Issue by chasezheng** [caesar0301/treelib#82]
for example,

```
>>> from treelib import Node, Tree
>>> tree = Tree()
>>> tree.create_node("Harry", "harry")  # root node
>>> tree.create_node("Jane", "jane", parent="harry")
>>> tree.create_node("Bill", "bill", parent="harry")
>>> tree.create_node("Diane", "diane", parent="jane")
>>> tree.create_node("Mary", "mary", parent="diane")
>>> tree.create_node("Mark", "mark", parent="jane")
>>> tree.show()
b'Harry\n\xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 Bill\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Jane\n    \xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 Diane\n    \xe2\x94\x82   \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Mary\n    \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 Mark\n'
```

To fix this, replace this line https://github.com/caesar0301/treelib/blob/1200ec1d7a1c5cda4508dddbfcc0bc13545ff575/treelib/tree.py#L679
with:
print(self.reader)

**Comment by LeBarbouze** [comment]
Hi, @chasezheng , I agree with your fix: I think the print() statement deals with encoding (well, the call to sys.stdout.write() does, it seems), so there is no need to encode before.

Maybe you could submit a PR with your fix?

**Comment by alazyworkaholic** [comment]
This issue drove me nuts for a couple hours until I found out it wasn't me or my system's fault. +1 for a fix please! This library is just what I needed otherwise.

**Comment by caesar0301** [comment]
Thanks guys!! :+1:

**Comment by AdenLe-Github** [comment]
print(self.reader.encode('utf-8')) is now on line 932

Replace with print(self._reader)
