### ISSUE TITLE
Modifying the identifier of a node is not working properly

### ISSUE THREAD

**Issue by nm1300** [caesar0301/treelib#84]
Hello,

```
tree = Tree()
tree.create_node("Harry", "harry")
tree.create_node("Jane", "jane", parent="harry")
n= tree.get_node("jane")
n.identifier=("xyz")

tree.get_node("xyz") ### returns None 
tree.get_node("jane") ### return a Node object whose identifier is "xyz" ! 
```

Hope you can address this, 

Thnaks.

**Comment by c0fec0de** [comment]
The `Tree` class maintains a internal `_nodes` dictionary which is not updated on identifier and other changes. 

You may want to use a reimplementation of treelib called [anytree](http://anytree.readthedocs.io)

    from anytree import Node
    from anytree import find_by_attr


    root = Node('harry')
    Node('jane', parent=root)
    n = find_by_attr(root, 'jane')
    n.name = 'xyz'

    find_by_attr(root, 'xyz')  ### returns     Node('/harry/xyz')
    find_by_attr(root, 'jane')  ### returns None

HTH

**Comment by nm1300** [comment]
Perfect, used anytree and it is solved now. many thanks.

**Comment by caesar0301** [comment]
Now treelib supports node attribute modification:

### Update non-root node
```python
from treelib import Tree, Node
tree = Tree()
tree.create_node("Harry", "harry")
tree.create_node("Jane", "jane", parent="harry")

tree.update_node("jane", identifier='xyz')
assert tree["xyz"].identifier == 'xyz'
```

### Update root node
```python
from treelib import Tree, Node
tree = Tree()
tree.create_node("Harry", "harry")
tree.create_node("Jane", "jane", parent="harry")

tree.update_node("harry", identifier='xyz')
assert tree.root == 'xyz'
assert tree['jane'].bpointer == 'xyz'
```
