### ISSUE TITLE
Restrictions for fork of treelib

### ISSUE THREAD

**Issue by vovanbo** [caesar0301/treelib#86]
Hi!

I've forked treelib and make many significant changes into library (inherit Tree from OrderedDict directly, simplify some methods, drop Python 2 support etc). So, do you have any restrictions for fork in case it will be released as separate lib (`ttree`) on PyPI? All copyrights and license will be remained.

I don't want to merge my changes into treelib, because of its very subjective. If some of my decisions make sense in treelib, I am ready to create some PRs.

Thank you!

p.s. [Link to fork](https://github.com/vovanbo/ttree)

**Comment by c0fec0de** [comment]
I rewrote it completly...

https://pypi.python.org/pypi/anytree

**Comment by vovanbo** [comment]
@c0fec0de Thank you for the link! I will discover your implementation.

I just released my fork as [ttree](https://pypi.python.org/pypi/ttree) on PyPI.
